targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            app_database: lib/services/database/app_database.dart
          schema_dir: lib/services/database/schema/
          store_date_time_values_as_text: true

      riverpod_generator:
        options:
          provider_name_suffix: "pod"
          provider_family_name_suffix: "pod"
